version: '3.4'

services:
  mongo:
    image: mongo:4.4.5
    restart: always
    ports:
      - "27017:27017"
  
  etls-characters:
    environment:
    - connectionString=mongodb://mongo:27017
    depends_on:    
    - mongo

  etls-locations:
    environment:
    - connectionString=mongodb://mongo:27017
    depends_on:    
    - mongo
  
  api:
    environment:
    - connectionString=mongodb://mongo:27017
    ports:
      - "5008:8080"
    depends_on:    
    - mongo
    - etls-characters
    - etls-locations

  web:
    # environment:
    # - connectionString=mongodb://mongo:27017
    ports:
      - "3000:80"
    depends_on:    
    - api