version: '3.4'

services:
  etls-characters:
    image: ${DOCKER_REGISTRY:-rickandmorty}/charactersintegration:${TAG:-latest}
    build:
      context: .
      dockerfile: etls/charactersIntegrator/Dockerfile
  etls-locations:
    image: ${DOCKER_REGISTRY:-rickandmorty}/locationsintegration:${TAG:-latest}
    build:
      context: .
      dockerfile: etls/locationsIntegrator/Dockerfile
  api:
    image: ${DOCKER_REGISTRY:-rickandmorty}/api:${TAG:-latest}
    build:
      context: .
      dockerfile: apiV1/Dockerfile